In [1]:
import torch

# create tensor

In [2]:
my_tensor=torch.tensor([[1,2,3],[3,4,5]])

In [3]:
my_tensor

tensor([[1, 2, 3],
        [3, 4, 5]])

In [4]:
my_tensor=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [5]:
my_tensor=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device="cuda")
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [6]:
my_tensor=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device="cpu")
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
print("type==",my_tensor.dtype)

type== torch.float32


In [8]:
print("shape===",my_tensor.shape)

shape=== torch.Size([2, 3])


In [9]:
print("device==",my_tensor.device)

device== cpu


In [12]:
torch.zeros(size=(5,6))

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [13]:
torch.ones(size=(3,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [14]:
torch.ones(size=(3,5))+2

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])

In [15]:
torch.eye(10)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
torch.rand((5,3))

tensor([[0.3983, 0.3836, 0.5094],
        [0.9473, 0.1585, 0.3951],
        [0.4416, 0.3210, 0.3264],
        [0.8107, 0.3970, 0.6504],
        [0.8380, 0.1082, 0.7675]])

In [17]:
torch.arange(40,100,4)

tensor([40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96])

In [18]:
import numpy as np

In [19]:
np.random.randint(2,6,10)

array([2, 3, 5, 5, 5, 2, 4, 5, 2, 3])

In [20]:
torch.randint(2,6,(2,5))

tensor([[5, 4, 2, 5, 2],
        [5, 3, 5, 3, 5]])

In [21]:
npInt=np.random.randint(2,6,10)
npInt

array([2, 2, 5, 3, 5, 3, 4, 4, 3, 3])

In [22]:
torch.tensor(npInt)

tensor([2, 2, 5, 3, 5, 3, 4, 4, 3, 3], dtype=torch.int32)

In [23]:
a=torch.linspace(2,10,100)
a

tensor([ 2.0000,  2.0808,  2.1616,  2.2424,  2.3232,  2.4040,  2.4848,  2.5657,
         2.6465,  2.7273,  2.8081,  2.8889,  2.9697,  3.0505,  3.1313,  3.2121,
         3.2929,  3.3737,  3.4545,  3.5354,  3.6162,  3.6970,  3.7778,  3.8586,
         3.9394,  4.0202,  4.1010,  4.1818,  4.2626,  4.3434,  4.4242,  4.5051,
         4.5859,  4.6667,  4.7475,  4.8283,  4.9091,  4.9899,  5.0707,  5.1515,
         5.2323,  5.3131,  5.3939,  5.4747,  5.5556,  5.6364,  5.7172,  5.7980,
         5.8788,  5.9596,  6.0404,  6.1212,  6.2020,  6.2828,  6.3636,  6.4444,
         6.5253,  6.6061,  6.6869,  6.7677,  6.8485,  6.9293,  7.0101,  7.0909,
         7.1717,  7.2525,  7.3333,  7.4141,  7.4949,  7.5758,  7.6566,  7.7374,
         7.8182,  7.8990,  7.9798,  8.0606,  8.1414,  8.2222,  8.3030,  8.3838,
         8.4646,  8.5455,  8.6263,  8.7071,  8.7879,  8.8687,  8.9495,  9.0303,
         9.1111,  9.1919,  9.2727,  9.3535,  9.4343,  9.5152,  9.5960,  9.6768,
         9.7576,  9.8384,  9.9192, 10.00

In [24]:
torch.logspace(2,10,100)

tensor([1.0000e+02, 1.2045e+02, 1.4508e+02, 1.7475e+02, 2.1049e+02, 2.5354e+02,
        3.0539e+02, 3.6784e+02, 4.4306e+02, 5.3367e+02, 6.4281e+02, 7.7426e+02,
        9.3260e+02, 1.1233e+03, 1.3530e+03, 1.6298e+03, 1.9630e+03, 2.3645e+03,
        2.8480e+03, 3.4305e+03, 4.1320e+03, 4.9770e+03, 5.9948e+03, 7.2208e+03,
        8.6975e+03, 1.0476e+04, 1.2619e+04, 1.5199e+04, 1.8307e+04, 2.2051e+04,
        2.6561e+04, 3.1993e+04, 3.8535e+04, 4.6416e+04, 5.5908e+04, 6.7342e+04,
        8.1113e+04, 9.7701e+04, 1.1768e+05, 1.4175e+05, 1.7074e+05, 2.0565e+05,
        2.4771e+05, 2.9836e+05, 3.5938e+05, 4.3288e+05, 5.2140e+05, 6.2803e+05,
        7.5646e+05, 9.1116e+05, 1.0975e+06, 1.3219e+06, 1.5923e+06, 1.9179e+06,
        2.3101e+06, 2.7826e+06, 3.3516e+06, 4.0370e+06, 4.8626e+06, 5.8570e+06,
        7.0548e+06, 8.4975e+06, 1.0235e+07, 1.2328e+07, 1.4850e+07, 1.7886e+07,
        2.1544e+07, 2.5950e+07, 3.1257e+07, 3.7649e+07, 4.5349e+07, 5.4623e+07,
        6.5793e+07, 7.9248e+07, 9.5455e+

In [25]:
mm=torch.arange(4)
mm

tensor([0, 1, 2, 3])

In [26]:
mm.bool()

tensor([False,  True,  True,  True])

In [27]:
mm.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [28]:
mm.dtype

torch.int64

In [29]:
mm.long()

tensor([0, 1, 2, 3])

In [30]:
mm.float()

tensor([0., 1., 2., 3.])

In [31]:
mm.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [32]:
mm

tensor([0, 1, 2, 3])

In [33]:
mm.numpy()

array([0, 1, 2, 3], dtype=int64)

In [34]:
x=torch.tensor([1,2,3])
y=torch.tensor([9,8,7])

In [35]:
z1=torch.empty(3)

In [36]:
torch.add(y,x,out=z1)

tensor([10., 10., 10.])

In [37]:
z1

tensor([10., 10., 10.])

In [38]:
z2=torch.add(x,y)
z2

tensor([10, 10, 10])

In [39]:
z3=x+y
z3

tensor([10, 10, 10])

In [40]:
z=y-x
z

tensor([8, 6, 4])

In [41]:
z=x/y
z

tensor([0.1111, 0.2500, 0.4286])

In [42]:
z=torch.true_divide(x,y)
z

tensor([0.1111, 0.2500, 0.4286])

In [43]:
t=torch.zeros(3)
t

tensor([0., 0., 0.])

In [44]:
t.add_(x)

tensor([1., 2., 3.])

In [45]:
t

tensor([1., 2., 3.])

In [46]:
z=x.pow(2)
z

tensor([1, 4, 9])

In [47]:
z=x**2
z

tensor([1, 4, 9])

In [49]:
z<5

tensor([ True,  True, False])

In [50]:
x1=torch.rand((2,5))
x2=torch.rand((5,3))

In [51]:
print(x1)

tensor([[0.3276, 0.1843, 0.2237, 0.8968, 0.9821],
        [0.8351, 0.9159, 0.5908, 0.7474, 0.6695]])


In [52]:
print(x2)

tensor([[0.6061, 0.3185, 0.2361],
        [0.8303, 0.0255, 0.4651],
        [0.6625, 0.7414, 0.6571],
        [0.4397, 0.6899, 0.2296],
        [0.0731, 0.1441, 0.0217]])


In [53]:
x1.mm(x2)

tensor([[0.9659, 1.0351, 0.5372],
        [2.0357, 1.3395, 1.1975]])

In [54]:
torch.mm(x1,x2)

tensor([[0.9659, 1.0351, 0.5372],
        [2.0357, 1.3395, 1.1975]])

In [55]:
x=torch.tensor([1,2,3])
y=torch.tensor([9,8,7])
z=x*y
z

tensor([ 9, 16, 21])

In [56]:
torch.dot(x,y)

tensor(46)

In [57]:
x1=torch.rand((5,5))

In [58]:
x1

tensor([[0.0119, 0.6599, 0.7907, 0.4057, 0.4127],
        [0.2066, 0.4440, 0.4244, 0.2492, 0.6418],
        [0.9617, 0.9588, 0.4062, 0.4313, 0.8637],
        [0.8183, 0.8225, 0.9808, 0.8516, 0.8581],
        [0.4799, 0.9161, 0.5703, 0.7969, 0.8533]])

In [61]:
torch.sum(x1,dim=0)

tensor([2.4784, 3.8013, 3.1725, 2.7348, 3.6296])

In [63]:
values,indict=torch.max(x1,dim=1)

In [64]:
values

tensor([0.7907, 0.6418, 0.9617, 0.9808, 0.9161])

In [65]:
indict

tensor([2, 4, 0, 2, 1])

In [66]:
torch.argmax(x1,dim=1)

tensor([2, 4, 0, 2, 1])

In [67]:
torch.mean(x1,dim=0)

tensor([0.4957, 0.7603, 0.6345, 0.5470, 0.7259])

In [68]:
x

tensor([1, 2, 3])

In [69]:
y

tensor([9, 8, 7])

In [70]:
torch.eq(x,y)

tensor([False, False, False])

In [72]:
torch.sort(x,descending=True)

torch.return_types.sort(
values=tensor([3, 2, 1]),
indices=tensor([2, 1, 0]))

In [73]:
x

tensor([1, 2, 3])

In [76]:
torch.clamp(x,min=10)

tensor([10, 10, 10])

In [80]:
x=torch.tensor([1,1,1,1,1,1],dtype=bool)
x

tensor([True, True, True, True, True, True])

In [81]:
torch.any(x)

tensor(True)

In [82]:
torch.all(x)

tensor(True)

In [83]:
x

tensor([True, True, True, True, True, True])

In [84]:
x.shape

torch.Size([6])

In [85]:
t=torch.randint(2,20,(3,4))
t

tensor([[ 7,  7, 16, 17],
        [ 8, 17, 15, 12],
        [ 5, 10,  8,  9]])

In [89]:
t.reshape(2,6)

tensor([[ 7,  7, 16, 17,  8, 17],
        [15, 12,  5, 10,  8,  9]])

In [90]:
t

tensor([[ 7,  7, 16, 17],
        [ 8, 17, 15, 12],
        [ 5, 10,  8,  9]])

In [94]:
t.reshape(3,-1)

tensor([[ 7,  7, 16, 17],
        [ 8, 17, 15, 12],
        [ 5, 10,  8,  9]])

In [95]:
t=t.view(-1)
t

tensor([ 7,  7, 16, 17,  8, 17, 15, 12,  5, 10,  8,  9])

In [99]:
t[2:-2]

tensor([16, 17,  8, 17, 15, 12,  5, 10])